version: '3.3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./:/usr/src/
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
  web:
    image: nginx:1.17.9-alpine
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/src/app/static
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/:/usr/src/app/
      - static:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=myproject_dev
    env_file:
      - ./.env.prod
volumes:
  postgres_data:
  static:
