version: '3.7'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./:/usr/src/
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
  web:
    image: nginx:1.17.9-alpine
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=myproject_dev
    env_file:
      - ./.env.dev
volumes:
  postgres_data:
